ENV['PATH'] = '/usr/local/opt/node@18/bin:' + ENV['PATH']
ENV['NODE_BINARY'] = '/usr/local/opt/node@18/bin/node'


require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :dynamic   # do NOT use use_modular_headers! anywhere

target 'klatchup' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each { |bc| bc.build_settings['CLANG_ENABLE_MODULES'] = 'YES' }
    end
  end
end

